CREATE TABLE users (
                       id SERIAL PRIMARY KEY,
                       name VARCHAR(255),
                       email VARCHAR(255),
                       password VARCHAR(255),
                       phone VARCHAR(50),
                       home_address VARCHAR(255),
                       office_address VARCHAR(255),
                       preferred_arrival_start TIME,
                       preferred_arrival_end TIME,
                       flexibility_minutes INTEGER,
                       flexibility_km DOUBLE PRECISION,
                       role VARCHAR(255)
);

CREATE TABLE driver (
                        id INTEGER PRIMARY KEY REFERENCES users(id),
                        available_seats INTEGER,
                        cost_per100kmeur DOUBLE PRECISION
);

CREATE TABLE passenger (
                           id INTEGER PRIMARY KEY REFERENCES users(id)
);

CREATE TABLE rides (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO rides(name) VALUES ('SofiaPlovdiv'), ('OfficeX');

-- -- NOTE: example bcrypt hashes below. Generate real ones with your PasswordEncoder and replace them.
-- INSERT INTO users (id, name, email, password, phone, home_address, office_address, preferred_arrival_start,
--                    preferred_arrival_end, flexibility_minutes, flexibility_km, role)
-- VALUES
--     (1, 'Alice Driver', 'alice@car.com', '$2a$10$CjwK6XkZc6dYz8Qp1s2heO0b1d3f5g7h9jK1L2m3N4o5P6q7R8sUe', '+359888111001', 'Tsarigradsko Shose 115, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 15, 5.0, 'DRIVER'),
--     (2, 'Bob Driver', 'bob@car.com',   '$2a$10$CjwK6XkZc6dYz8Qp1s2heO0b1d3f5g7h9jK1L2m3N4o5P6q7R8sUe', '+359888111002', 'Slivnitsa Blvd 150, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 20, 7.0, 'DRIVER'),
--     (3, 'Carol Driver', 'carol@car.com', '$2a$10$CjwK6XkZc6dYz8Qp1s2heO0b1d3f5g7h9jK1L2m3N4o5P6q7R8sUe', '+359888111003', 'Mladost 1, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:15:00', '09:15:00', 10, 4.0, 'DRIVER'),
--     (4, 'David Driver', 'david@car.com', '$2a$10$CjwK6XkZc6dYz8Qp1s2heO0b1d3f5g7h9jK1L2m3N4o5P6q7R8sUe', '+359888111004', 'Nadezhda 2, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 15, 6.0, 'DRIVER'),
--     (5, 'Eve Driver', 'eve@car.com',     '$2a$10$CjwK6XkZc6dYz8Qp1s2heO0b1d3f5g7h9jK1L2m3N4o5P6q7R8sUe', '+359888111005', 'Obelya, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:10:00', '09:10:00', 12, 5.5, 'DRIVER'),
--
--     (6, 'Tom Passenger', 'tom@bus.com',   '$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222001', 'Lozenets, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:30:00', '09:30:00', 10, 3.0, 'PASSENGER'),
--     (7, 'Jane Passenger', 'jane@bus.com', '$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222002', 'Druzhba 1, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:20:00', '09:20:00', 8, 2.5, 'PASSENGER'),
--     (8, 'Ivan Passenger', 'ivan@bus.com', '$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222003', 'Gotse Delchev, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 15, 4.5, 'PASSENGER'),
--     (9, 'Maria Passenger', 'maria@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222004', 'Studentski Grad, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:05:00', '09:05:00', 10, 3.2, 'PASSENGER'),
--     (10,'Peter Passenger', 'peter@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222005', 'Hadzhi Dimitar, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:15:00', '09:15:00', 12, 4.0, 'PASSENGER'),
--     (11,'Anna Passenger', 'anna@bus.com', '$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222006', 'Lyulin 3, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 20, 6.0, 'PASSENGER'),
--     (12,'Nikolay Passenger','nikolay@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222007', 'Banishora, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:10:00', '09:10:00', 12, 4.8, 'PASSENGER'),
--     (13,'Elena Passenger','elena@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222008', 'Geo Milev, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:25:00', '09:25:00', 7, 2.8, 'PASSENGER'),
--     (14,'Todor Passenger','todor@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222009', 'Zapaden Park, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:00:00', '09:00:00', 15, 5.5, 'PASSENGER'),
--     (15,'Kristina Passenger','kristina@bus.com','$2a$10$pQxYz1B4H2uG3vFh9kLmN2pQxY2uG3vFh9kLmN2pQxYz1B4H2b', '+359888222010', 'Ovcha Kupel, Sofia, Bulgaria', 'Cherni Vrah Blvd 51, Sofia, Bulgaria', '08:10:00', '09:10:00', 10, 3.6, 'PASSENGER');
--
-- INSERT INTO driver (id, available_seats, cost_per100kmeur) VALUES
--                                                                   (1, 3, 10.0),
--                                                                   (2, 2, 12.0),
--                                                                   (3, 4, 9.5),
--                                                                   (4, 3, 11.0),
--                                                                   (5, 2, 10.5);
--
-- INSERT INTO passenger (id) VALUES
--                                (6),(7),(8),(9),(10),(11),(12),(13),(14),(15);
